from typing import List
from fastapi import status
"""
nexus-anomaly-detection-api — AutoGen Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.autogen_tool import nexus_autogen_register
    nexus_autogen_register(agent)
"""

from typing import Annotated, Any

from ._mcp_client import call_mcp_tool

def open_multivariate_anomaly_session(variable_names: Annotated[list[str], 'List of variable names to monitor. Must contain at least 2 elements.'], sampling_interval_ms: Annotated[float, 'Sampling interval in milliseconds between observations.'], takens_embedding_dim: Annotated[float, "Embedding dimension for Takens' reconstruction."], takens_delay_tau: Annotated[float, "Delay tau for Takens' embedding."], kde_bandwidth_method: Annotated[str, "KDE bandwidth estimation method. Allowed: 'scott', 'silverman', 'plugin'."], te_window_size: Annotated[float, 'Window size (number of observations) for Transfer Entropy computation.'], nmi_lag_max: Annotated[float, 'Maximum lag for Normalized Mutual Information.']) -> Any:
    """Initialize a new anomaly detection session for a set of time-series variables. Use this when starting real-time causal anomaly monitoring across multiple variables (min 2). Do NOT use for single-variable anomaly detection; use univariate methods instead. Specify Takens embedding and KDE bandwidth parameters to configure the TE/NMI computation engine. Returns a session_id required for subsequent operations."""
    return call_mcp_tool("nexus_anomaly_detection_api_open_multivariate_anomaly_session", {"variable_names": variable_names, "sampling_interval_ms": sampling_interval_ms, "takens_embedding_dim": takens_embedding_dim, "takens_delay_tau": takens_delay_tau, "kde_bandwidth_method": kde_bandwidth_method, "te_window_size": te_window_size, "nmi_lag_max": nmi_lag_max})

def ingest_sliding_window_observations(session_id: Annotated[str, 'The session ID returned by open_multivariate_anomaly_session.'], observations: Annotated[list[list[float]], '2D array of observations, shape [timesteps, variables] matching variable order.'], timestamps_iso: Annotated[list[str], 'ISO 8601 timestamps corresponding to each row of observations.'], flush_partial_window: Annotated[bool, 'If true, force computation on any buffered partial window.']) -> Any:
    """Push a batch of multivariate observations (sliding window data) into an active anomaly detection session. Provide synchronized timestamps in ISO format. Use this to continuously feed data into the session. Do NOT use to replace historical data; it's for live streaming. The flush_partial_window flag forces computation of a partial window. Returns buffer status and number of ready windows."""
    return call_mcp_tool("nexus_anomaly_detection_api_ingest_sliding_window_observations", {"session_id": session_id, "observations": observations, "timestamps_iso": timestamps_iso, "flush_partial_window": flush_partial_window})

def stream_causal_anomaly_events(session_id: Annotated[str, 'The session ID.'], nmi_anomaly_threshold: Annotated[float, 'Threshold for the NMI-based anomaly score (0 to 1).'], te_net_flow_min: Annotated[float, 'Minimum net Transfer Entropy flow (TE_forward - TE_reverse) to consider an edge as causal.'], max_events: Annotated[float, 'Maximum number of events to return.']) -> Any:
    """Retrieve detected causal anomaly events from a session's computation pipeline. Specify NMI anomaly threshold and minimum net Transfer Entropy flow to filter events. Use this to pull detected anomalies that indicate a causal origin. Do NOT use for raw anomaly scores only; for causal map resolution, use resolve_anomaly_causal_map. Returns array of events with origin node and propagation depth."""
    return call_mcp_tool("nexus_anomaly_detection_api_stream_causal_anomaly_events", {"session_id": session_id, "nmi_anomaly_threshold": nmi_anomaly_threshold, "te_net_flow_min": te_net_flow_min, "max_events": max_events})

def resolve_anomaly_causal_map(session_id: Annotated[str, 'The session ID.'], event_id: Annotated[str, 'The event ID from stream_causal_anomaly_events.'], include_reverse_te: Annotated[bool, 'If true, include reverse TE values in the output.'], min_net_te_weight: Annotated[float, 'Minimum net TE weight for an edge to be included.']) -> Any:
    """Resolve the detailed causal graph for a specific anomaly event previously detected. Set include_reverse_te to true if you need both directions of Transfer Entropy; set min_net_te_weight to filter weak edges. Use this to understand propagation paths from the origin node. Do NOT use for browsing events; use stream_causal_anomaly_events first to get event_ids. Returns adjacency and edge weights."""
    return call_mcp_tool("nexus_anomaly_detection_api_resolve_anomaly_causal_map", {"session_id": session_id, "event_id": event_id, "include_reverse_te": include_reverse_te, "min_net_te_weight": min_net_te_weight})

def close_anomaly_session(session_id: Annotated[str, 'The session ID to close.'], export_session_summary: Annotated[bool, 'If true, include a session summary in the response.']) -> Any:
    """Terminate an active session and optionally export a summary of all observations and events. Use this when monitoring ends. Do NOT call on already closed sessions. After closure, the session_id is invalidated and data is archived."""
    return call_mcp_tool("nexus_anomaly_detection_api_close_anomaly_session", {"session_id": session_id, "export_session_summary": export_session_summary})


def nexus_autogen_register(agent) -> None:
    """Register all nexus-anomaly-detection-api tools on an AutoGen agent."""
    agent.register_for_llm(name="nexus_anomaly_detection_api_open_multivariate_anomaly_session", description='Initialize a new anomaly detection session for a set of time-series variables. Use this when starting real-time causal anomaly monitoring across multiple variables (min 2). Do NOT use for single-variable anomaly detection; use univariate methods instead. Specify Takens embedding and KDE bandwidth parameters to configure the TE/NMI computation engine. Returns a session_id required for subsequent operations.')(open_multivariate_anomaly_session)
    agent.register_for_execution(name="nexus_anomaly_detection_api_open_multivariate_anomaly_session")(open_multivariate_anomaly_session)
    agent.register_for_llm(name="nexus_anomaly_detection_api_ingest_sliding_window_observations", description="Push a batch of multivariate observations (sliding window data) into an active anomaly detection session. Provide synchronized timestamps in ISO format. Use this to continuously feed data into the session. Do NOT use to replace historical data; it's for live streaming. The flush_partial_window flag forces computation of a partial window. Returns buffer status and number of ready windows.")(ingest_sliding_window_observations)
    agent.register_for_execution(name="nexus_anomaly_detection_api_ingest_sliding_window_observations")(ingest_sliding_window_observations)
    agent.register_for_llm(name="nexus_anomaly_detection_api_stream_causal_anomaly_events", description="Retrieve detected causal anomaly events from a session's computation pipeline. Specify NMI anomaly threshold and minimum net Transfer Entropy flow to filter events. Use this to pull detected anomalies that indicate a causal origin. Do NOT use for raw anomaly scores only; for causal map resolution, use resolve_anomaly_causal_map. Returns array of events with origin node and propagation depth.")(stream_causal_anomaly_events)
    agent.register_for_execution(name="nexus_anomaly_detection_api_stream_causal_anomaly_events")(stream_causal_anomaly_events)
    agent.register_for_llm(name="nexus_anomaly_detection_api_resolve_anomaly_causal_map", description='Resolve the detailed causal graph for a specific anomaly event previously detected. Set include_reverse_te to true if you need both directions of Transfer Entropy; set min_net_te_weight to filter weak edges. Use this to understand propagation paths from the origin node. Do NOT use for browsing events; use stream_causal_anomaly_events first to get event_ids. Returns adjacency and edge weights.')(resolve_anomaly_causal_map)
    agent.register_for_execution(name="nexus_anomaly_detection_api_resolve_anomaly_causal_map")(resolve_anomaly_causal_map)
    agent.register_for_llm(name="nexus_anomaly_detection_api_close_anomaly_session", description='Terminate an active session and optionally export a summary of all observations and events. Use this when monitoring ends. Do NOT call on already closed sessions. After closure, the session_id is invalidated and data is archived.')(close_anomaly_session)
    agent.register_for_execution(name="nexus_anomaly_detection_api_close_anomaly_session")(close_anomaly_session)