from typing import List
from fastapi import status
"""
nexus-anomaly-detection-api — LangChain Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.langchain_tool import open_multivariate_anomaly_session_tool, ingest_sliding_window_observations_tool, stream_causal_anomaly_events_tool, resolve_anomaly_causal_map_tool, close_anomaly_session_tool
    agent = initialize_agent([open_multivariate_anomaly_session_tool, ingest_sliding_window_observations_tool, stream_causal_anomaly_events_tool, resolve_anomaly_causal_map_tool, close_anomaly_session_tool], llm,
                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)
"""

from typing import Any
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class OpenMultivariateAnomalySessionInput(BaseModel):
    variable_names: list[str] = Field(..., description='List of variable names to monitor. Must contain at least 2 elements.')
    sampling_interval_ms: float = Field(..., description='Sampling interval in milliseconds between observations.')
    takens_embedding_dim: float = Field(..., description="Embedding dimension for Takens' reconstruction.")
    takens_delay_tau: float = Field(..., description="Delay tau for Takens' embedding.")
    kde_bandwidth_method: str = Field(..., description="KDE bandwidth estimation method. Allowed: 'scott', 'silverman', 'plugin'.")
    te_window_size: float = Field(..., description='Window size (number of observations) for Transfer Entropy computation.')
    nmi_lag_max: float = Field(..., description='Maximum lag for Normalized Mutual Information.')


def _open_multivariate_anomaly_session_impl(variable_names, sampling_interval_ms, takens_embedding_dim, takens_delay_tau, kde_bandwidth_method, te_window_size, nmi_lag_max) -> Any:
    return call_mcp_tool("nexus_anomaly_detection_api_open_multivariate_anomaly_session", {"variable_names": variable_names, "sampling_interval_ms": sampling_interval_ms, "takens_embedding_dim": takens_embedding_dim, "takens_delay_tau": takens_delay_tau, "kde_bandwidth_method": kde_bandwidth_method, "te_window_size": te_window_size, "nmi_lag_max": nmi_lag_max})


open_multivariate_anomaly_session_tool = StructuredTool.from_function(
    func=_open_multivariate_anomaly_session_impl,
    name="nexus_anomaly_detection_api_open_multivariate_anomaly_session",
    description='Initialize a new anomaly detection session for a set of time-series variables. Use this when starting real-time causal anomaly monitoring across multiple variables (min 2). Do NOT use for single-variable anomaly detection; use univariate methods instead. Specify Takens embedding and KDE bandwidth parameters to configure the TE/NMI computation engine. Returns a session_id required for subsequent operations.',
    args_schema=OpenMultivariateAnomalySessionInput,
)

class IngestSlidingWindowObservationsInput(BaseModel):
    session_id: str = Field(..., description='The session ID returned by open_multivariate_anomaly_session.')
    observations: list[list[float]] = Field(..., description='2D array of observations, shape [timesteps, variables] matching variable order.')
    timestamps_iso: list[str] = Field(..., description='ISO 8601 timestamps corresponding to each row of observations.')
    flush_partial_window: bool = Field(..., description='If true, force computation on any buffered partial window.')


def _ingest_sliding_window_observations_impl(session_id, observations, timestamps_iso, flush_partial_window) -> Any:
    return call_mcp_tool("nexus_anomaly_detection_api_ingest_sliding_window_observations", {"session_id": session_id, "observations": observations, "timestamps_iso": timestamps_iso, "flush_partial_window": flush_partial_window})


ingest_sliding_window_observations_tool = StructuredTool.from_function(
    func=_ingest_sliding_window_observations_impl,
    name="nexus_anomaly_detection_api_ingest_sliding_window_observations",
    description="Push a batch of multivariate observations (sliding window data) into an active anomaly detection session. Provide synchronized timestamps in ISO format. Use this to continuously feed data into the session. Do NOT use to replace historical data; it's for live streaming. The flush_partial_window flag forces computation of a partial window. Returns buffer status and number of ready windows.",
    args_schema=IngestSlidingWindowObservationsInput,
)

class StreamCausalAnomalyEventsInput(BaseModel):
    session_id: str = Field(..., description='The session ID.')
    nmi_anomaly_threshold: float = Field(..., description='Threshold for the NMI-based anomaly score (0 to 1).')
    te_net_flow_min: float = Field(..., description='Minimum net Transfer Entropy flow (TE_forward - TE_reverse) to consider an edge as causal.')
    max_events: float = Field(..., description='Maximum number of events to return.')


def _stream_causal_anomaly_events_impl(session_id, nmi_anomaly_threshold, te_net_flow_min, max_events) -> Any:
    return call_mcp_tool("nexus_anomaly_detection_api_stream_causal_anomaly_events", {"session_id": session_id, "nmi_anomaly_threshold": nmi_anomaly_threshold, "te_net_flow_min": te_net_flow_min, "max_events": max_events})


stream_causal_anomaly_events_tool = StructuredTool.from_function(
    func=_stream_causal_anomaly_events_impl,
    name="nexus_anomaly_detection_api_stream_causal_anomaly_events",
    description="Retrieve detected causal anomaly events from a session's computation pipeline. Specify NMI anomaly threshold and minimum net Transfer Entropy flow to filter events. Use this to pull detected anomalies that indicate a causal origin. Do NOT use for raw anomaly scores only; for causal map resolution, use resolve_anomaly_causal_map. Returns array of events with origin node and propagation depth.",
    args_schema=StreamCausalAnomalyEventsInput,
)

class ResolveAnomalyCausalMapInput(BaseModel):
    session_id: str = Field(..., description='The session ID.')
    event_id: str = Field(..., description='The event ID from stream_causal_anomaly_events.')
    include_reverse_te: bool = Field(..., description='If true, include reverse TE values in the output.')
    min_net_te_weight: float = Field(..., description='Minimum net TE weight for an edge to be included.')


def _resolve_anomaly_causal_map_impl(session_id, event_id, include_reverse_te, min_net_te_weight) -> Any:
    return call_mcp_tool("nexus_anomaly_detection_api_resolve_anomaly_causal_map", {"session_id": session_id, "event_id": event_id, "include_reverse_te": include_reverse_te, "min_net_te_weight": min_net_te_weight})


resolve_anomaly_causal_map_tool = StructuredTool.from_function(
    func=_resolve_anomaly_causal_map_impl,
    name="nexus_anomaly_detection_api_resolve_anomaly_causal_map",
    description='Resolve the detailed causal graph for a specific anomaly event previously detected. Set include_reverse_te to true if you need both directions of Transfer Entropy; set min_net_te_weight to filter weak edges. Use this to understand propagation paths from the origin node. Do NOT use for browsing events; use stream_causal_anomaly_events first to get event_ids. Returns adjacency and edge weights.',
    args_schema=ResolveAnomalyCausalMapInput,
)

class CloseAnomalySessionInput(BaseModel):
    session_id: str = Field(..., description='The session ID to close.')
    export_session_summary: bool = Field(..., description='If true, include a session summary in the response.')


def _close_anomaly_session_impl(session_id, export_session_summary) -> Any:
    return call_mcp_tool("nexus_anomaly_detection_api_close_anomaly_session", {"session_id": session_id, "export_session_summary": export_session_summary})


close_anomaly_session_tool = StructuredTool.from_function(
    func=_close_anomaly_session_impl,
    name="nexus_anomaly_detection_api_close_anomaly_session",
    description='Terminate an active session and optionally export a summary of all observations and events. Use this when monitoring ends. Do NOT call on already closed sessions. After closure, the session_id is invalidated and data is archived.',
    args_schema=CloseAnomalySessionInput,
)